name = "strava-api"
main = "src/worker.ts"
compatibility_date = "2023-07-17"

kv_namespaces = [
    { binding = "STRAVA_DATA",  id = "PASTE_YOUR_COPIED_KV_NAMESPACE_ID_HERE }
]

[vars]
ATHLETE_ID = "000000000"
CLIENT_ID = "110851"
GOALS = "{\"Walk\":250,\"Ride\":500}"
CALLBACK_URL = "http://link-to-api.workers.dev/callback"
PASSWORD = "SomePassword1234"

#SECRETS
#[ACCESS_TOKEN]
#[CLIENT_SECRET]
