name = "strava-api"
main = "src/worker.ts"
compatibility_date = "2023-07-17"

kv_namespaces = [
    { binding = "STRAVA_DATA",  id = "ID_TO_KV", preview_id = "PREVIEW_ID" }
]

[vars]
ATHLETE_ID = "000000000"
CLIENT_ID = "110851"
GOALS = "{\"Walk\":250,\"Ride\":500}"
CALLBACK_URL = "http://link-to-api.workers.dev/callback"
PASSWORD = "SomePassword1234"
